### ISSUE TITLE
Unspecified dependency after publishing to Bintray

### ISSUE THREAD

**Issue by zaclimon** [StefMa/bintray-release#4]
Hello! Thank you for the library, it has been mostly a saver for those of us who are considering using newer versions of Gradle but couldn't get the Novoda plugin to work accordingly. I tried to publish a newer version of my libraries to Bintray, but I have some unspecified null dependencies on my POM files.

File 1:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.zaclimon</groupId>
  <artifactId>xipl</artifactId>
  <version>0.2.2</version>
  <packaging>aar</packaging>
  <dependencies>
    <dependency>
      <groupId>null</groupId>
      <artifactId>unspecified</artifactId>
      <version>null</version>
      <scope>compile</scope>
    </dependency>
   ...
</project>
```

File 2:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.zaclimon</groupId>
  <artifactId>tiflibrary</artifactId>
  <version>0.2.2</version>
  <packaging>aar</packaging>
  <dependencies>
    <dependency>
      <groupId>null</groupId>
      <artifactId>unspecified</artifactId>
      <version>null</version>
      <scope>compile</scope>
    </dependency>
   ...
</project>
```

I mostly use a generic `publish.gradle` and define the `artifactId` and `desc` for my libraries inside their own `build.gradle`. This worked on the original Novoda plugin.

The source for the related Gradle scripts are available below:

https://github.com/zaclimon/xipl/blob/46a777508dca48f53bc40c7a83bca31b94143ff0/gradle/publish.gradle
https://github.com/zaclimon/xipl/blob/46a777508dca48f53bc40c7a83bca31b94143ff0/library/build.gradle#L39
https://github.com/zaclimon/xipl/blob/46a777508dca48f53bc40c7a83bca31b94143ff0/tiflibrary/build.gradle#L47

Do you have any idea what might be the root cause? In the worst case, I could still adjust both projects separately like in the project's README.

Thanks! :smiley:

**Comment by StefMa** [comment]
Hey,

can you pls post your **full** POM file?
I would like to know *which* dependencies leads to "null" and "unspecified".

The files you posted doesn't reflect the configuration I'do describe in the readme.
You have to set the `gradle project version & group`. Otherwise it will not work:
```
group = "com.zaclimon"
version = "0.2.2"
publish {
  // Other configurations
}
```

You also have to do this in both libraries. Cause you use a `project()` dependency...

**Comment by StefMa** [comment]
The issue was not because of the `publish.gradle` you have mentioned but of the `filetree` dependency.
See [this issue](https://github.com/zaclimon/xipl/pull/13).

I've created a issue in the root project [here](https://github.com/StefMa/AndroidArtifacts/issues/39).

If you have still issues feel free to comment or create a new issue 👍

**Comment by zaclimon** [comment]
That's perfect, thank you for looking into this! I'll let you know if I find any new issues.
